const GENERATION_ACTION_TYPE = {
  FETCH_STARTED: "FETCH_GENERATION_STARTED",
  FETCH_SUCCEEDED: "FETCH_GENERATION_SUCCEEDED",
  FETCH_FAILED: "FETCH_GENERATION_FAILED"
};

const DRAGON_ACTION_TYPE = {
  FETCH_STARTED: "FETCH_DRAGON_STARTED",
  FETCH_SUCCEEDED: "FETCH_DRAGON_SUCCEEDED",
  FETCH_FAILED: "FETCH_DRAGON_FAILED"
};

const ACCOUNT_ACTION_TYPE = {
  FETCH_STARTED: "FETCH_ACCOUNT_STARTED",
  FETCH_FAILED: "FETCH_ACCOUNT_SUCCEEDED",

  // LOGOUT_FETCH_FAILED: "ACCOUNT_LOGOUT_FAILED",
  LOGOUT_FETCH_SUCCEEDED: "ACCOUNT_LOGOUT_SUCCEEDED",

  // LOGIN_FETCH_FAILED: "ACCOUNT_LOGIN_FAILED",
  LOGIN_FETCH_SUCCEEDED: "ACCOUNT_LOGIN_SUCCEEDED",

  // SIGNUP_FETCH_FAILED: "ACCOUNT_SIGNUP_FAILED",
  SIGNUP_FETCH_SUCCEEDED: "ACCOUNT_SIGNUP_SUCCEEDED",

  // AUTHENTICATED_FETCH_FAILED: "ACCOUNT_AUTHENTICATED_FAILED",
  AUTHENTICATED_FETCH_SUCCEEDED: "ACCOUNT_AUTHENTICATED_SUCCEEEDED"
};

const ACCOUNT_DRAGONS_ACTION_TYPE = {
  FETCH_STARTED: "FETCH_ACCOUNT_DRAGON_STARTED",
  FETCH_SUCCEEDED: "FETCH_ACCOUNT_DRAGON_SUCCEEDED",
  FETCH_FAILED: "FETCH_ACCOUNT_DRAGON_FAILED"
};

export {
  GENERATION_ACTION_TYPE,
  DRAGON_ACTION_TYPE,
  ACCOUNT_ACTION_TYPE,
  ACCOUNT_DRAGONS_ACTION_TYPE
};
