const GENERATION_ACTION_TYPE = {
    FETCH_STARTED: 'FETCH_GENERATION_STARTED',
    FETCH_SUCCEEDED: 'FETCH_GENERATION_SUCCEEDED',
    FETCH_FAILED: 'FETCH_GENERATION_FAILED'
};

const DRAGON_ACTION_TYPE = {
    FETCH_STARTED: 'FETCH_DRAGON_STARTED',
    FETCH_SUCCEEDED: 'FETCH_DRAGON_SUCCEEDED',
    FETCH_FAILED: 'FETCH_DRAGON_FAILED'
};

export {GENERATION_ACTION_TYPE, DRAGON_ACTION_TYPE};